language: go

go:
- 1.15.5

env:
- GO111MODULE=auto

script: go test -v ./... && bash <(curl -s https://codecov.io/bash) -t token


after_success:
  - bash <(curl -s https://codecov.io/bash) -t ${CODECOV_TOKEN}

git:
  depth: 1

branches:
  only:
    - release-2.0.0